"""change self referncing relationship in Department model

Revision ID: 34f77864cbde
Revises: 30bbe6ce3a9a
Create Date: 2026-02-21 11:32:36.523824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f77864cbde'
down_revision: Union[str, Sequence[str], None] = '30bbe6ce3a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
