"""Add default ordering by full name for Employee relation in Department model

Revision ID: 3a07b869afd6
Revises: cf5c93480de1
Create Date: 2026-02-22 17:46:41.061194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a07b869afd6'
down_revision: Union[str, Sequence[str], None] = 'cf5c93480de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
