"""Add loading strategy for self referencing FK field in Department model

Revision ID: 459cdb4b9b6c
Revises: b6aa560e7b5a
Create Date: 2026-02-22 11:36:03.618471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '459cdb4b9b6c'
down_revision: Union[str, Sequence[str], None] = 'b6aa560e7b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
