"""Add casacde delition param on department_id FK field for Employee model

Revision ID: 4dcf8d673b00
Revises: 3a07b869afd6
Create Date: 2026-02-23 10:45:06.819064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dcf8d673b00'
down_revision: Union[str, Sequence[str], None] = '3a07b869afd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employees_department_id_fkey'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('employees_department_id_fkey'), 'employees', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###
