"""Add loading strategy for Department model

Revision ID: b6aa560e7b5a
Revises: d0feee6cd0f4
Create Date: 2026-02-22 11:33:19.337183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6aa560e7b5a'
down_revision: Union[str, Sequence[str], None] = 'd0feee6cd0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
