"""Remove default ordering for Employee relation in Department model

Revision ID: cf5c93480de1
Revises: 8940d3e7f4f4
Create Date: 2026-02-22 17:30:10.411111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5c93480de1'
down_revision: Union[str, Sequence[str], None] = '8940d3e7f4f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
