"""change FK reference between Department and Employee models

Revision ID: d0feee6cd0f4
Revises: d2848ebb6b5e
Create Date: 2026-02-22 11:12:17.269887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0feee6cd0f4'
down_revision: Union[str, Sequence[str], None] = 'd2848ebb6b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
